name: Tag and Release on PR Merge 

on:
  pull_request:
    types: [closed]
    
jobs:
  tag_on_merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Tag
        run: |
          $tagName = "${{ github.event.pull_request.title }}" 
          $tagMessage = "${{ github.event.pull_request.body }}"
          echo "TAG_NAME=$tagName" | Out-File -FilePath $env:GITHUB_ENV -Append
          git tag -a "$tagName" -m "$tagMessage"
          git push origin "$tagName"     



      - name: Create the release on the new Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ env.TAG_NAME }}
        run: |
          gh release create "$env:TAG_NAME" --generate-notes
