on:
  pull_request:
    types: [closed]

jobs:
  tag_on_merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Tag
        run: |
          TAG_NAME="${{ github.event.pull_request.title }}" 
          TAG_MESSAGE="${{ github.event.pull_request.body }}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag -a "$TAG_NAME" -m "$TAG_MESSAGE"
          git push origin "$TAG_NAME"

      - name: git release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ env.TAG_NAME}}
        run: |
          gh release create  "$TAG_NAME" --generate-notes 

      
